<a href="https://colab.research.google.com/github/jayasooryantm/tensorflow_certification/blob/main/Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Funtamentals of Tensorflow

* Intro to tensors
* Getting info from tensors
* Manipulating tensors
* Tensors & NumPy
* Using @tf.function (speed up the regular python functions)
* Using GPUs/TPUs with tensorflow


In [1]:
import tensorflow as tf
print(tf.__version__)

2.8.0


In [2]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
scalar.ndim

0

In [4]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
matrix = tf.constant([[10, 7],
                      [10, 7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [10,  7]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
another_matrix = tf.constant([[10., 10.],
                             [5., 5.]], 
                             dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10., 10.],
       [ 5.,  5.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
tensor = tf.constant([[[1, 2, 4],
                       [1, 2, 3]],
                     [[1, 2, 3],
                      [1, 2, 3]],
                      [[1, 2, 3],
                       [1, 2, 3]]], dtype=tf.float32)
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
array([[[1., 2., 4.],
        [1., 2., 3.]],

       [[1., 2., 3.],
        [1., 2., 3.]],

       [[1., 2., 3.],
        [1., 2., 3.]]], dtype=float32)>

In [11]:
tensor.ndim

3

### Creating tensors with tf.Variable

In [12]:
var = tf.Variable([10, 10])
const = tf.constant([10 , 10])

In [13]:
var, const

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>)

In [14]:
#changing one of the element in var
var[0].assign(5)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([ 5, 10], dtype=int32)>

In [15]:
#Wont' work, because there is no function called assign in constant.
#-- const[0].assign(5)

### Creating random tensors with tensorflow

In [16]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

### Shuffle the order in a tensor

In [17]:
tf.random.shuffle(random_1)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [-0.23193765, -1.8107855 ],
       [ 0.07595026, -1.2573844 ]], dtype=float32)>

### Other ways to create tensors

In [18]:
tf.ones([10, 8])

<tf.Tensor: shape=(10, 8), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [19]:
tf.zeros([10, 9])

<tf.Tensor: shape=(10, 9), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [20]:
import numpy as np
numpy_array = np.arange(1, 25, dtype=np.int32)

In [21]:
numpy_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [22]:
tf.constant(numpy_array, shape=(2, 3, 4))

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

## Getting info from tensors

In [23]:
#Matrix multiplication
tensorOne = tf.random.normal((5, 6))
tensorTwo = tf.random.normal((6, 5))

In [24]:
%%timeit
tf_method = tf.matmul(tensorOne, tensorTwo)

The slowest run took 16993.05 times longer than the fastest. This could mean that an intermediate result is being cached.
1 loop, best of 5: 89.1 µs per loop


In [25]:
%%timeit
py_method = tensorOne @ tensorTwo

10000 loops, best of 5: 102 µs per loop


In [26]:
tf.tensordot(tensorOne, tensorTwo, 1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.26536092,  0.04108912,  0.86562383,  0.6509414 , -0.65473235],
       [ 1.2593392 ,  2.594152  ,  5.979897  ,  4.9296    , -3.7130704 ],
       [ 2.175611  , -0.7438742 , -1.7437255 , -0.1827892 , -0.9847698 ],
       [-5.411737  ,  0.08436865,  0.5234587 , -4.2446995 ,  3.685472  ],
       [-3.717807  ,  0.88280684,  0.17071365, -3.3024282 ,  4.268225  ]],
      dtype=float32)>

### Changing the tensor datatypes

In [27]:
float32_type = tf.constant(tf.random.normal((50000, 600)))

In [28]:
float16_type = tf.cast(float32_type, dtype= tf.float16)

In [29]:
import sys
sys.getsizeof(float32_type), sys.getsizeof(float16_type)

(184, 184)

### Aggregating tensors

In [30]:
tensor = np.random.randn(100) 

In [31]:
tensor

array([ 3.89725702e-01, -1.54510144e+00, -1.62734709e+00,  1.24879761e-01,
       -1.22196905e+00,  9.66991293e-01,  1.73822266e-01,  9.27201793e-02,
        1.60503792e+00, -1.55381127e+00, -1.65284929e+00,  1.03662909e+00,
       -8.90987238e-01,  8.95944289e-01,  1.42784484e+00,  7.38506063e-01,
        7.85271163e-01,  1.32875543e+00, -4.07127026e-01,  3.09295950e-01,
        2.00811285e+00,  6.50243677e-01,  5.89283001e-01,  9.10689292e-01,
        1.05248022e+00,  3.75846385e-01, -6.46634676e-01, -1.90747384e-01,
        5.59595905e-01,  1.00206041e+00,  1.59088211e+00,  8.49070031e-01,
        2.01902504e-01, -4.63674717e-02,  3.15862758e-01,  7.51936839e-01,
       -7.85326807e-01,  1.78405215e+00, -1.26355403e+00, -6.51397876e-01,
       -3.51426232e-01, -7.53698287e-01,  9.89300624e-01, -1.03782561e+00,
        1.14227445e+00, -8.92325529e-01,  8.82499977e-01, -7.36139640e-01,
       -3.45236538e-01,  1.10937050e+00, -2.09599083e+00,  2.33212355e+00,
       -6.21342533e-01,  

In [32]:
tf.reduce_min(tensor)

<tf.Tensor: shape=(), dtype=float64, numpy=-2.4686463252635504>

In [33]:
tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=float64, numpy=2.6576607593352457>

In [34]:
tf.reduce_sum(tensor)

<tf.Tensor: shape=(), dtype=float64, numpy=20.69810330872474>

In [35]:
tf.reduce_mean(tensor)

<tf.Tensor: shape=(), dtype=float64, numpy=0.20698103308724738>

### Sqeezing a tensor (removing the single dimensions)

In [36]:
tf.random.set_seed(0)
data = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
data

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.29197514, 0.20656645, 0.53539073, 0.5612575 , 0.4166745 ,
           0.80782795, 0.4932251 , 0.99812925, 0.69673514, 0.1253736 ,
           0.7098167 , 0.6624156 , 0.57225657, 0.36475348, 0.42051828,
           0.630057  , 0.913813  , 0.6616472 , 0.83347356, 0.08395803,
           0.2797594 , 0.0155232 , 0.72637355, 0.7655387 , 0.6798667 ,
           0.53272796, 0.7565141 , 0.04742193, 0.05037141, 0.75174344,
           0.1727128 , 0.3119352 , 0.29137385, 0.10051239, 0.16567075,
           0.7696651 , 0.58567977, 0.98200965, 0.9148327 , 0.14166534,
           0.09756553, 0.6062784 , 0.17792177, 0.518052  , 0.9821211 ,
           0.17577946, 0.04563165, 0.59754145, 0.5629543 , 0.80507433]]]]],
      dtype=float32)>

In [37]:
data.shape

TensorShape([1, 1, 1, 1, 50])

In [38]:
data_squeezed = tf.squeeze(data)
data_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.29197514, 0.20656645, 0.53539073, 0.5612575 , 0.4166745 ,
       0.80782795, 0.4932251 , 0.99812925, 0.69673514, 0.1253736 ,
       0.7098167 , 0.6624156 , 0.57225657, 0.36475348, 0.42051828,
       0.630057  , 0.913813  , 0.6616472 , 0.83347356, 0.08395803,
       0.2797594 , 0.0155232 , 0.72637355, 0.7655387 , 0.6798667 ,
       0.53272796, 0.7565141 , 0.04742193, 0.05037141, 0.75174344,
       0.1727128 , 0.3119352 , 0.29137385, 0.10051239, 0.16567075,
       0.7696651 , 0.58567977, 0.98200965, 0.9148327 , 0.14166534,
       0.09756553, 0.6062784 , 0.17792177, 0.518052  , 0.9821211 ,
       0.17577946, 0.04563165, 0.59754145, 0.5629543 , 0.80507433],
      dtype=float32)>

In [39]:
rand_list = [0, 1, 0, 3]

tf.one_hot(rand_list, 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [40]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [42]:
!nvidia-smi

Thu Feb 17 14:23:46 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P0    63W / 149W |    707MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------