<a href="https://colab.research.google.com/github/jayasooryantm/tensorflow_certification/blob/main/Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Funtamentals of Tensorflow

* Intro to tensors
* Getting info from tensors
* Manipulating tensors
* Tensors & NumPy
* Using @tf.function (speed up the regular python functions)
* Using GPUs/TPUs with tensorflow


In [1]:
import tensorflow as tf
print(tf.__version__)

2.8.0


In [3]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
scalar.ndim

0

In [6]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
vector.ndim

1

In [8]:
matrix = tf.constant([[10, 7],
                      [10, 7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [10,  7]], dtype=int32)>

In [9]:
matrix.ndim

2

In [11]:
another_matrix = tf.constant([[10., 10.],
                             [5., 5.]], 
                             dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10., 10.],
       [ 5.,  5.]], dtype=float16)>

In [12]:
another_matrix.ndim

2

In [14]:
tensor = tf.constant([[[1, 2, 4],
                       [1, 2, 3]],
                     [[1, 2, 3],
                      [1, 2, 3]],
                      [[1, 2, 3],
                       [1, 2, 3]]], dtype=tf.float32)
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
array([[[1., 2., 4.],
        [1., 2., 3.]],

       [[1., 2., 3.],
        [1., 2., 3.]],

       [[1., 2., 3.],
        [1., 2., 3.]]], dtype=float32)>

In [15]:
tensor.ndim

3

### Creating tensors with tf.Variable

In [16]:
var = tf.Variable([10, 10])
const = tf.constant([10 , 10])

In [17]:
var, const

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>)

In [18]:
#changing one of the element in var
var[0].assign(5)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([ 5, 10], dtype=int32)>

In [20]:
const[0].assign(5)

AttributeError: ignored

### Creating random tensors with tensorflow

In [23]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

### Shuffle the order in a tensor

In [24]:
tf.random.shuffle(random_1)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.07595026, -1.2573844 ],
       [-0.7565803 , -0.06854702],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

### Other ways to create tensors

In [25]:
tf.ones([10, 8])

<tf.Tensor: shape=(10, 8), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [26]:
tf.zeros([10, 9])

<tf.Tensor: shape=(10, 9), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [29]:
import numpy as np
numpy_array = np.arange(1, 25, dtype=np.int32)

In [30]:
numpy_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [31]:
tf.constant(numpy_array, shape=(2, 3, 4))

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

## Getting info from tensors